import { onCall } from "firebase-functions/v2/https";
import { db, loadConfig, requireString, requireUid } from "../lib/admin.js";
import { readUserContext, serverClock, toMillis, txnSink } from "../lib/engine.js";
import { redeem, spin } from "../lib/rewards.js";
import { applyWrites } from "../lib/writes.js";
import { rethrow } from "./learning.js";
import type { RedemptionDoc, RewardDoc, SpinStateDoc } from "../types.js";

export const spinWheel = onCall(async (request) => {
  const uid = requireUid(request);
  const config = await loadConfig();
  const stateRef = db.doc(`spinState/${uid}`);
  const preview = await stateRef.get();
  const expectedSpins = (preview.get("totalSpins") as number | undefined) ?? 0;
  return db.runTransaction(async (txn) => {
    const ctx = await readUserContext(txn, uid, `spin_${uid}_${expectedSpins + 1}`, config);
    const stateSnap = await txn.get(stateRef);
    try {
      const { writes, result } = spin({
        ctx,
        clock: serverClock(ctx.now),
        state: stateSnap.exists ? (stateSnap.data() as SpinStateDoc) : null,
        expectedSpins,
        nextSpinAtMs: toMillis(stateSnap.get("nextSpinAt")),
        random: Math.random()
      });
      applyWrites(txnSink(txn), writes);
      return result;
    } catch (error) {
      return rethrow(error);
    }
  });
});

/**
 * redemptionKey is generated by the client per click, so a network retry of the same click
 * resolves to the same redemption without a second deduction.
 */
export const redeemReward = onCall(async (request) => {
  const uid = requireUid(request);
  const data = (request.data ?? {}) as { rewardId?: unknown; redemptionKey?: unknown };
  const rewardId = requireString(data.rewardId, "rewardId", 120);
  const redemptionKey = requireString(data.redemptionKey, "redemptionKey", 80);
  const config = await loadConfig();
  const redemptionId = `${uid}_${redemptionKey}`;
  return db.runTransaction(async (txn) => {
    const ctx = await readUserContext(txn, uid, `redeem_${redemptionId}`, config);
    const [rewardSnap, existingSnap, priorSnap] = await Promise.all([
      txn.get(db.doc(`rewards/${rewardId}`)),
      txn.get(db.doc(`redemptions/${redemptionId}`)),
      txn.get(db.collection("redemptions").where("userId", "==", uid).where("rewardId", "==", rewardId).limit(1))
    ]);
    try {
      const { writes, result } = redeem({
        ctx,
        clock: serverClock(ctx.now),
        reward: rewardSnap.exists ? (rewardSnap.data() as RewardDoc) : null,
        redemptionKey,
        existing: existingSnap.exists ? (existingSnap.data() as RedemptionDoc) : null,
        redeemedBefore: !priorSnap.empty,
        streakCurrent: ctx.streak.current
      });
      applyWrites(txnSink(txn), writes);
      return result;
    } catch (error) {
      return rethrow(error);
    }
  });
});
